# Generated by Django 4.2.16 on 2024-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='ANO',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='adicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='entidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='part_porc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Part. %'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='smmlv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='smmlv3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='smmlv4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_de_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
