# Generated by Django 4.2.16 on 2024-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contrato_ano_alter_contrato_adicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='acta_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
